blank_issues_enabled: false
contact_links:
  - name: Ask the community for help
    url: https://community.cratedb.com/
    about: Need help troubleshooting? Check out our guide on how to ask
  - name: Contact CrateDB Cloud and CrateDB Enterprise support
    url: https://support.cratedb.com/
    about: Are you using CrateDB Cloud? Contact our support team for help!
  - name: General CrateDB support information
    url: https://cratedb.com/support
    about: About CrateDB support contacts and knowledge
